baseURL = 'https://maxcohen31.github.io/'
languageCode = 'en-us'
#title = "Max's blog"
metaDataFormat = "yaml"
theme = "blowfish"
ignoreErrors = ["error-disable-taxonomy"]

[params.author]
menu_item_separator = " | "
description = "Computer Science student"
avatar = "/img/picme.jpg"

[params]
  customCSS = ["css/custom.css"]

[[menu.main]]
name = "Home"
url = "/"

[[menu.main]]
name = "About"
url = "/about/"

[[menu.main]]
name = "Posts"
url = "/posts/"

[params.social]
icon = "github"
name = "Github"
url = "https://github.com/maxcohen31"

